
# i wonder if we can use LeetCode problems to test our LLMs?
# Is there an API we can call for rtht?

"""
I get the distinct impression that running arbitrary code generated by LLMs is risky business.
I will have to contact project lead about how to proceed. Perhaps utilize a sandbox environment of some sort?

- Guojia La
"""